Add sync_certificates lane to iOS deployment Fastfile
game-ci/documentation pull request #302
Opened 2022-06-15 19:56 UTC by lazerwalker

#### Changes

As per @davidmfinol in Discord, this ads the `sync_certificates` fastlane lane (being referenced in the workflow) to the actual Fastfile. 

It also makes sure we’re consistently calling `bundle exec fastlane ios [command]` instead of just `bundle exec fastlane [command]`.he latter will work consistently on a Fastlane project with just iOS, but in a project with both iOS and Android it may fail depending on which platform has been set to the default. There’s no real downside to us being more verbose + precise.

#### Checklist

- [x] Read the contribution [guide](../blob/main/CONTRIBUTING.md) and accept the
      [code](../blob/main/CODE_OF_CONDUCT.md) of conduct
- [x] Readme (updated or not needed)
- [x] Tests (added, updated or not needed)

2022-06-15 20:08 UTC, lazerwalker commented
Hmm, this potentially seems like a spurious Vercel failure unrelated to the PR contents?

2022-06-15 20:23 UTC, davidmfinol requested changes
I think the environment variable names need to match what is used elsewhere

2022-06-15 20:23 UTC, davidmfinol commented on docs/03-github/06-deployment/ios.mdx
> +      app_identifier: ENV["BUNDLE_ID"]
```suggestion
      app_identifier: ENV["IOS_BUNDLE_ID"]
```

2022-06-15 20:23 UTC, davidmfinol commented on docs/03-github/06-deployment/ios.mdx
> +      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
```suggestion
      key_id: ENV["APPSTORE_KEY_ID"],
```

2022-06-15 20:23 UTC, davidmfinol commented on docs/03-github/06-deployment/ios.mdx
> +      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
```suggestion
      issuer_id: ENV["APPSTORE_ISSUER_ID"],
```

2022-06-15 20:23 UTC, davidmfinol commented on docs/03-github/06-deployment/ios.mdx
> +      key_content: ENV['APP_STORE_CONNECT_KEY']
```suggestion
      key_content: ENV['APPSTORE_P8']
```

2022-06-15 21:59 UTC, lazerwalker commented
@davidmfinol d'oh, thanks for catching that -- I double-checked that the `match_org` and `match_repo` Ruby vars existed in our context, but didn't bother to look at those env vars 🤦🏻 

Also didn't realize that GH's "commit suggestion" UI would generate 4 separate git commits, happy to squash if you care.

2022-06-16 00:07 UTC, davidmfinol approved these changes

2022-06-16 00:08 UTC, merged